version: 0.1

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y jq
      - sudo apt-get clean
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - bash commands.sh